volumes:
  pgdata:
  nginx:

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - nginx:/django
    ports: 
      - 8000:8000
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  django:
    container_name: django
    build: .. 
    expose:
      - 8080
    depends_on:
      - postgres
      - nginx
    env_file:
      - .env
    volumes:
      - nginx:/app/nginx
