# Generated by Django 5.1.2 on 2024-10-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('name', 'description')},
        ),
    ]
